version: '3.9'

services:
  php-fpm:
    container_name: systemio-test-serov-php-fpm
    user: '1000:1000'

    build:
      context: ./
      dockerfile: docker/php-fpm/Dockerfile

    volumes:
      - type: bind
        source: ./
        target: /var/www/html/

    command: /bin/sh -c "composer install
      && php-fpm"

    env_file: .env


  postgres:
    container_name: systemio-test-serov-postgres
    image: postgres:16-alpine3.19

    environment:
      POSTGRES_DB: systemio-test-serov
      POSTGRES_PASSWORD: postgres

    ports:
      - target: 5432
        published: $PG_CONTAINER_PUBLISHED_PORT
