version: '3.9'

services:
  php-fpm:
    container_name: systemio-test-serov-php-fpm
    depends_on:
      - postgres
    user: '1000:1000'

    build:
      context: ./
      dockerfile: docker/php-fpm/Dockerfile

    volumes:
      - type: bind
        source: ./
        target: /var/www/html/

    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      PHP_IDE_CONFIG: serverName=systemio-test-serov
    ports:
      - target: 80
        published: $PHP_SERVER_PUBLISHED_PORT

    command: /bin/sh -c "composer install
      && ./docker/php-fpm/wait-for-postgres.sh postgres postgres   
      && ./bin/console doctrine:database:create --if-not-exists --no-interaction
      && ./bin/console doctrine:schema:update --force --no-interaction
      && ./bin/console doctrine:migrations:migrate --no-interaction
      && php -S 0.0.0.0:80 -t /var/www/html/public"

    env_file: .env

  postgres:
    container_name: systemio-test-serov-postgres
    image: postgres:16-alpine3.19

    environment:
      POSTGRES_DB: systemio-test-serov
      POSTGRES_PASSWORD: postgres

    ports:
      - target: 5432
        published: $PG_CONTAINER_PUBLISHED_PORT
