parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Controller\:
        resource: '../src/Controller/'

    App\Service\:
        resource: '../src/Service/'

    Systemeio\TestForCandidates\PaymentProcessor\PaypalPaymentProcessor:

    Systemeio\TestForCandidates\PaymentProcessor\StripePaymentProcessor: